routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
 */

Route::get('/', function () {
    if (Auth::check()) {
        if (Auth::user()->role->role_name == 'trainer') {
            return redirect('smsLogs');
        } else {
            return redirect('projects');
        }
    } else {
        return redirect('projects');
    }

});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::group(['prefix' => 'projects/{project}'], function () {
    Route::match(['get', 'post'], '/response/{filter}/{type?}', ['as' => 'projects.response.filter', 'uses' => 'SurveyResultsController@responseRateSample']);
    Route::match(['get', 'post'], '/double', ['as' => 'projects.response.double', 'uses' => 'SurveyResultsController@responseRateDouble']);
    Route::match(['get', 'post'], '/useorigin/{survey_id}/{column}', ['as' => 'projects.response.origin.use', 'uses' => 'SurveyResultsController@originUse']);
    Route::match(['get', 'post'], '/usedouble/{survey_id}/{column}', ['as' => 'projects.response.double.use', 'uses' => 'SurveyResultsController@doubleUse']);
    Route::get('/search/sample', ['as' => 'projects.sample.search', 'uses' => 'ProjectController@search']);
    Route::get('/sampledata/{sampledata}/form/{formid}', ['as' => 'projects.incident.create', 'uses' => 'ProjectController@addIncident']);
    Route::get('/analysis', ['as' => 'projects.analysis', 'uses' => 'SurveyResultsController@analysis']);
    Route::match(['get','post'],'/smslog', ['as' => 'projects.smslog', 'uses' => 'ProjectController@smslog']);
    Route::get('/export', ['as' => 'projects.export', 'uses' => 'ProjectController@export']);
    Route::post('/import', ['as' => 'projects.import', 'uses' => 'ProjectController@import']);
    Route::get('/create-views', ['as' => 'projects.createviews', 'uses' => 'ProjectController@createAllViews']);
    Route::post('/trainingmode', ['as' => 'projects.trainingmode', 'uses' => 'ProjectController@trainingmode']);
    Route::post('/addlogic', ['as' => 'projects.logic', 'uses' => 'ProjectController@addLogic']);
    Route::post('/upload', ['as' => 'projects.upload.samples', 'uses' => 'ProjectController@uploadSamples']);
    Route::match(['get','post'],'/getcsv', ['as' => 'projects.getcsv', 'uses' => 'API\SmsAPIController@getcsv']);
    Route::get('/channel-rate', ['as' => 'projects.channel.rates', 'uses' => 'ProjectController@channelRates']);

    Route::get('location-metas/show-structure', ['as' => 'location-metas.show-structure', 'uses' => 'LocationMetaController@editStructure']);

    Route::match(['post','patch'],'location-metas/edit-structure', ['as' => 'location-metas.edit-structure', 'uses' => 'LocationMetaController@createOrUpdateStructure']);

    Route::resource('sample-details', 'SampleDetailsController');
});

Route::group(['prefix' => 'projects/{project}/surveys'], function () {

    Route::match(['get', 'post'], '/{sample_type?}', ['as' => 'projects.surveys.index', 'uses' => 'SurveyResultsController@index']);

    Route::get('/{result}/create/{form_id?}/{sample_type?}', ['as' => 'projects.surveys.create', 'uses' => 'SurveyResultsController@create']);

    Route::post('/{result}/save/{form_id?}/{sample_type?}', ['as' => 'projects.surveys.save', 'uses' => 'SurveyResultsController@save']);

    Route::get('/{result}', ['as' => 'projects.surveys.show', 'uses' => 'SurveyResultsController@show']);

    // Route::get('/{sample_id}/edit', ['as' => 'projects.surveys.edit', 'uses' => 'SurveyResultsController@edit']);

    Route::match(['put', 'patch'], '/{result}', ['as' => 'projects.surveys.update', 'uses' => 'SurveyResultsController@update']);

    Route::delete('/{result}', ['as' => 'projects.surveys.destroy', 'uses' => 'SurveyResultsController@destroy']);

});

Route::post('projects/{project}/dbcreate', ['as' => 'projects.dbcreate', 'uses' => ProjectController::class . '@dbcreate']);

Route::get('projects/sort/{project}', ['as' => 'projects.sort', 'uses' => ProjectController::class . '@sort']);

Route::get('projects/migrate', ['as' => 'projects.migrate', 'uses' => ProjectController::class . '@migrate']);

Route::post('projects/import', ['as' => 'projects.import', 'uses' => ProjectController::class . '@import']);


Route::resource('projects', 'ProjectController');

Route::post('questions', ['as' => 'questions.store', 'uses' => QuestionController::class . '@store']);

Route::post('questions/sort', ['as' => 'questions.sort', 'uses' => QuestionController::class . '@sort']);

Route::match(['put', 'patch'], 'questions/{question}', ['as' => 'questions.update', 'uses' => QuestionController::class . '@update']);

Route::delete('questions/{question}', ['as' => 'questions.destroy', 'uses' => QuestionController::class . '@destroy']);

//Route::resource('questions', 'QuestionController');

Route::resource('smsLogs', 'SmsLogController');

Route::match(['get','post'], 'smslogs', ['as' => 'smsLogs.index', 'uses' => 'SmsLogController@index']);

Route::post('translate/{id}', ['as' => 'translate', 'uses' => 'SettingController@translate']);

Route::post('settings/save', ['as' => 'settings.save', 'uses' => 'SettingController@save']);

Route::resource('settings', 'SettingController');

Route::post('sample/import', ['as' => 'sample.import', 'uses' => 'SampleDataController@import']);

Route::resource('sampleDatas', 'SampleDataController');

Route::resource('users', 'UserController');

Route::resource('roles', 'RoleController');

Route::resource('projectPhones', 'ProjectPhoneController');

Route::resource('observers', 'ObserverController');

Route::resource('logicalChecks', 'LogicalCheckController');


Route::resource('location-metas', 'LocationMetaController');

Route::post('translations/import',['as' => 'translations.import', 'uses' => 'TranslationController@import']);

Route::resource('translations', 'TranslationController');

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\ProjectDataTable;
use App\DataTables\SmsLogDataTable;
use App\Http\Requests\CreateProjectRequest;
use App\Http\Requests\UpdateProjectRequest;
use App\Models\LocationMeta;
use App\Models\LogicalCheck;
use App\Models\Observer;
use App\Models\Project;
use App\Models\Question;
use App\Models\Sample;
use App\Models\SampleData;
use App\Models\Section;
use App\Repositories\ProjectRepository;
use App\Scopes\OrderByScope;
use App\SmsHelper;
use App\Traits\QuestionsTrait;
use Carbon\Carbon;
use Flash;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use League\Csv\Reader;
use League\Csv\Statement;
use Maatwebsite\Excel\Facades\Excel;
use PhpOffice\PhpSpreadsheet\Reader\Xls;
use Ramsey\Uuid\Uuid;
use Response;
use Spatie\TranslationLoader\LanguageLine;

/**
 * Class ProjectController
 * @package App\Http\Controllers
 */
class ProjectController extends AppBaseController
{
    use QuestionsTrait;
    /**
     * @var  ProjectRepository
     */

    private $projectRepository;

    private $project;

    private $dbname;

    public function __construct(ProjectRepository $projectRepo)
    {
        $this->middleware('auth');
        $this->projectRepository = $projectRepo;
    }

    /**
     * Display a listing of the Project.
     *
     * @param ProjectDataTable $projectDataTable
     * @return Response
     */
    public function index(Project $project)
    {
        try {
            $this->authorize('index', Project::class);
        } catch (AuthorizationException $e) {
            Flash::error($e->getMessage());
            return redirect()->back();
        }


        return view('projects.index')
            ->with('projects', $project->all());
    }

    public function migrate()
    {
        $projects = $this->projectRepository->all();
        foreach ($projects as $project) {
            foreach ($project->sections as $sort => $section) {
                $section['sort'] = $sort;
                $sections_to_save[] = new Section($section);
            }

            $project->sections()->saveMany($sections_to_save);
            unset($sections_to_save);
        }

        DB::statement('update questions join sections on sections.sort=questions.section AND sections.project_id=questions.project_id set questions.section=sections.id');
    }

    /**
     * Show the form for creating a new Project.
     *
     * @return Response
     */
    public function create()
    {
        try {
            $this->authorize('create', Project::class);
        } catch (AuthorizationException $e) {
            Flash::error($e->getMessage());
            return redirect()->back();
        }
        return view('projects.create');
    }

    /**
     * Store a newly created Project in storage.
     *
     * @param CreateProjectRequest $request
     *
     * @return Response
     */
    public function store(CreateProjectRequest $request)
    {
        try {
            $this->authorize('create', Project::class);
        } catch (AuthorizationException $e) {
            Flash::error($e->getMessage());
            return redirect()->back();
        }

        $input = $request->except(['samples']);

        if (!isset($input['sections'])) {
            $input['sections'][0] = [
                'sectionname' => 'Survey',
            ];
        }

        $short_project_name = substr($input['project'], 0, 10);
        $short_project_name = preg_replace('/[^a-zA-Z0-9]/', '_', $short_project_name);
        $unique = uniqid();
        $short_unique = substr($unique, 0, 5);
        $input['dbname'] = snake_case(strtolower($short_project_name) . '_' . $short_unique);

        // $lang = config('app.fallback_locale');

        // $input['project_trans'] = json_encode([$lang => $input['project']]);

        $project = Project::create($input);

        $sections = $input['sections'];

        foreach ($sections as $sort => $section) {
            $section['sort'] = $sort;
            $sections_to_save[] = new Section($section);
        }

        $project->sections()->saveMany($sections_to_save);

        // update survey_inputs as s join questions as q on s.question_id = q.id join projects as p on q.project_id = p.id set s.double_entry = 1, q.double_entry = 1 where p.id = 1 and q.section = 1;

        foreach ($input['sections'] as $skey => $section) {
            if (!empty($section)) {
                if (isset($section['indouble'])) {
                    $query = "update survey_inputs as s join questions as q on s.question_id = q.id join projects as p on q.project_id = p.id set s.double_entry = 1, q.double_entry = 1 where p.id = $project->id and q.section = $skey";
                } else {
                    $query = "update survey_inputs as s join questions as q on s.question_id = q.id join projects as p on q.project_id = p.id set s.double_entry = 0, q.double_entry = 0 where p.id = $project->id and q.section = $skey";
                }
                DB::update(DB::raw($query));
            }
        }

        Flash::success('Project saved successfully.');

        return redirect(route('projects.index'));
    }

    /**
     * Display the specified Project.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $project = $this->projectRepository->findWithoutFail($id);

        try {
            $this->authorize('view', $project);
        } catch (AuthorizationException $e) {
            Flash::error($e->getMessage());
            return redirect()->back();
        }

        if (empty($project)) {
            Flash::error('Project not found');

            return redirect(route('projects.index'));
        }

        if ($project->status != 'published') {
            return redirect(route('projects.index'));
        }

        return view('projects.show')->with('project', $project)
            ->with('questions', $project->questions);
    }

    /**
     * Show the form for editing the specified Project.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $project = $this->projectRepository->findWithoutFail($id);
        try {
            $this->authorize('update', $project);
        } catch (AuthorizationException $e) {
            Flash::error($e->getMessage());
            return redirect()->back();
        }

        if (empty($project)) {
            Flash::error('Project not found');

            return redirect(route('projects.index'));
        }

        $observation_type = SampleData::pluck('observer_field', 'observer_field')->unique();


        $project->load(['inputs']);
        return view('projects.edit')
            ->with('project', $project)
            ->with('questions', $project->questions)
            ->with('observation_type', $observation_type);
    }

    /**
     * Update the specified Project in storage.
     *
     * @param  int $id
     * @param UpdateProjectRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateProjectRequest $request)
    {
        $project = $this->projectRepository->findWithoutFail($id);

        try {
            $this->authorize('update', $project);
        } catch (AuthorizationException $e) {
            Flash::error($e->getMessage());
            return redirect()->back();
        }

        if (empty($project)) {
            Flash::error('Project not found');

            return redirect(route('projects.index'));
        }

        $input = $request->except('samples', 'sections');

        if (Schema::hasTable($project->dbname)) {
            $input['status'] = 'modified';
        }

        // $lang = config('app.fallback_locale');
        // $project_trans = $project->project_trans;
        // if (!empty($project_trans) && array_key_exists($lang, $project_trans)) {
        //     $translation = $project_trans[$lang];
        // }
        // $new_translation = [$lang => $input['project']];
        // $input['project_trans'] = array_merge($new_translation, $translation);

        $project = $this->projectRepository->update($input, $id);

        $sections = $request->input('sections');

        if (empty($sections)) {
            $sections[0] = [
                'sectionname' => 'Survey',
            ];
        }

        $sectionsDb = $project->sections->pluck('id', 'id');

        foreach ($sections as $skey => $section) {
            if (!empty($section)) {
                $section['sort'] = $skey;
                // find section to update
                if (array_key_exists('sectionid', $section)) {
                    unset($sectionsDb[$section['sectionid']]);
                    $oldsection = Section::find($section['sectionid']);
                    $oldsection->sort = $skey;
                    $oldsection->sectionname = $section['sectionname'];
                    if (isset($section['layout'])) {
                        $oldsection->layout = $section['layout'];
                    }
                    if (isset($section['descriptions'])) {
                        $oldsection->descriptions = $section['descriptions'];
                    }
                    if (isset($section['indouble'])) {
                        $oldsection->indouble = true;
                    } else {
                        $oldsection->indouble = false;
                    }
                    if (isset($section['optional'])) {
                        $oldsection->optional = true;
                    } else {
                        $oldsection->optional = false;
                    }
                    if (isset($section['disablesms'])) {
                        $oldsection->disablesms = true;
                    } else {
                        $oldsection->disablesms = false;

resources/views/projects/box-item.blade.php
@php
    $response_filter =  '';
    if(!$project->locationMetas->isEmpty()) {
        if(!$project->locationMetas->where('filter_type', 'selectbox')->isEmpty()) {
            $response_filter = $project->locationMetas->where('filter_type', 'selectbox')->first()->field_name;
        }
    }
@endphp
<div class="box box-primary">
    <div class="box-body">
        <h4>{{ $project->project }}</h4>
        <div class="media">
            <div class="media-left">
                <a href="{{ route('projects.surveys.index', $project->id) }}">
                    <span style="background-color: #eee;height: auto;border-radius: 4px;box-shadow: 0 1px 3px rgba(0,0,0,.15);text-align: center;font-family: 'Lobster';font-size: 5vw;">{{ $project->unique_code }}</span>
                </a>
            </div>
            <div class="media-body">
                <div class="clearfix">
                    @if($project->type == 'sample2db')
                        <a href="{{ route('projects.surveys.index', $project->id) }}"
                           class='btn btn-success btn-sm' style='margin-bottom: 5px;'>
                            <i class="glyphicon glyphicon-eye-open"></i> {!! trans('messages.list_incidents') !!}
                        </a>
                    @else
                        <a href="{{ route('projects.surveys.index', $project->id) }}"
                           class='btn btn-success btn-sm' style='margin-bottom: 5px;'>
                            <i class="glyphicon glyphicon-eye-open"></i> {!! trans('messages.list_samples') !!}
                        </a>
                    @endif
                        <a href="{{ route('projects.response.filter', [$project->id, $response_filter]) }}"
                           class='btn btn-default btn-sm' style='margin-bottom: 5px;'>
                            <i class="glyphicon glyphicon-equalizer"></i> {!! trans('messages.response') !!}
                        </a>
                    @if(Auth::user()->role->level > 8)
                        <a href="{{ route('projects.edit', $project->id) }}" class='btn btn-default btn-sm'
                           style='margin-bottom: 5px;'>
                            <i class="glyphicon glyphicon-edit"></i> {!! trans('messages.edit') !!}
                        </a>
                    @endif
                    @if(Auth::user()->role->level >= 7)
                            <a href="{{ route('projects.channel.rates', [$project->id]) }}"
                               class='btn btn-default btn-sm' style='margin-bottom: 5px;'>
                                <i class="glyphicon glyphicon-equalizer"></i> {!! trans('messages.channel-rate') !!}
                            </a>
                        @if(config('sms.double_entry'))
                            <a href="{{ route('projects.response.filter', [$project->id, $response_filter, 'double']) }}"
                               class='btn btn-default btn-sm' style='margin-bottom: 5px;'>
                                <i class="glyphicon glyphicon-transfer"></i> {!! trans('messages.double_entry') !!}
                            </a>
                            <a href="{{ route('projects.response.double', [$project->id]) }}"
                               class='btn btn-default btn-sm' style='margin-bottom: 5px;'>
                                <i class="fa fa-balance-scale"></i> {!! trans('messages.check') !!}</i>
                            </a>
                        @endif
                        <a href="{{ route('projects.analysis', $project->id) }}"
                           class='btn btn-default btn-sm' style='margin-bottom: 5px;'>
                            <i class="fa fa-pie-chart"></i> {!! trans('messages.analysis') !!}
                        </a>
                        <a href="{{ route('projects.smslog', $project->id) }}" class='btn btn-default btn-sm' style='margin-bottom: 5px;'>
                        <i class="fa fa-envelope"></i> {!! trans('messages.smslog') !!}
                        </a>
                        <a href="{{ route('location-metas.show-structure', $project->id) }}"
                           class='btn btn-default btn-sm' style='margin-bottom: 5px;'>
                            <i class="glyphicon glyphicon-edit"></i>Edit Sample Columns
                        </a>

                        <a href="{{ route('sample-details.index', ['project_id' => $project->id]) }}"
                           class='btn btn-default btn-sm' style='margin-bottom: 5px;'>
                            <i class="glyphicon glyphicon-edit"></i>List Sample Data
                        </a>

                    @endif
                </div>
            </div>
            <div class="media-right">
                {!! Form::open(['route' => ['projects.destroy', $project->id], 'method' => 'delete', 'class' => 'from-inline']) !!}

                {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
                    'type' => 'submit',
                    'class' => 'btn btn-danger',
                    'style' => 'height: auto;border-radius: 4px;box-shadow: 0 1px 3px rgba(0,0,0,.15);text-align: center;font-family: "Lobster";font-size: 2vw;',
                    'onclick' => "return confirm('".trans('messages.are_you_sure')."')"
                ]) !!}

                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>

resources/views/projects/boxes.blade.php
@foreach($projects as $project)
    <div class="col-sm-12 @if($loop->count !== 1) col-md-6 @endif">
        @include('projects.box-item')
    </div>
@endforeach

resources/views/projects/channel-rate.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $project->project }}</title>
    <!-- Latest compiled and minified plotly.js JavaScript -->
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>


</head>
<body>
<div id="plot"></div>
<div id="plot2"></div>
<script>
    // Plotly.d3.csv("https://raw.githubusercontent.com/plotly/datasets/master/finance-charts-apple.csv", function(err, rows){
    //
    //     function unpack(rows, key) {
    //         return rows.map(function(row) { return row[key]; });
    //     }
    //
    //
    //     var trace1 = {
    //         type: "scatter",
    //         mode: "lines",
    //         name: 'AAPL High',
    //         x: unpack(rows, 'Date'),
    //         y: unpack(rows, 'AAPL.High'),
    //         line: {color: '#17BECF'}
    //     }
    //
    //     var trace2 = {
    //         type: "scatter",
    //         mode: "lines",
    //         name: 'AAPL Low',
    //         x: unpack(rows, 'Date'),
    //         y: unpack(rows, 'AAPL.Low'),
    //         line: {color: '#7F7F7F'}
    //     }
    //
    //     var data = [trace1,trace2];
    //     console.log(data);
    //     var layout = {
    //         title: 'Basic Time Series',
    //     };
    //
    //     Plotly.newPlot('plot', data, layout);
    // })

    function getFirstData() {
        var ajaxurl = "{{ route('project.responses', [$project->id]) }}";

        var start_time = "{!! $start_time !!}"
        jQuery.ajax({
            type: "get",
            url: ajaxurl,
            dataType : 'JSON',
            cache: "false",
            success: function(response){
                if(response.success) {
                    var ySMS = [0];
                    var yWeb = [0];

                    var sms_channel_time = [start_time];
                    var web_channel_time = [start_time];

                    jQuery.each(response.data, function (index, value) {

                        if(value.channel == 'sms') {
                            sms_channel_time.push(value.sms_time_slice);
                            ySMS.push(value.sms_channel_count);

                        }

                        if(value.channel == 'web') {
                            web_channel_time.push(value.web_time_slice);
                            yWeb.push(value.web_channel_count);
                        }

                    });
                    trace1 = {
                        type: "linear",
                        //mode: "lines",
                        name: 'SMS',
                        x: sms_channel_time,
                        y: ySMS,
                        line: {color: '#17BECF'}
                    }

                    trace2 = {
                        type: "linear",
                        //mode: "lines",
                        name: 'Web',
                        x: web_channel_time,
                        y: yWeb,
                        line: {color: '#7F7F7F'}
                    }
                    drawChart(trace1,trace2);
                }
            }
        });

    }
    var trace1 = {};
    var trace2 = {};
    getFirstData();

    function drawChart(trace1,trace2) {
        var data = [trace1,trace2];
        console.log(data);

        var layout = {
            title: '{{ $project->project }} response rate by report channel',
        };

        Plotly.newPlot('plot2', data, layout);
    }

    setInterval(function(){getFirstData();}, 3000);
</script>
</body>
</html>

resources/views/projects/datatables_actions.blade.php
<div class="row">
    <div class="col-sm-4">
        <div class="row">
            <div class='btn-group'>
                @if($type == 'sample2db')
                    <a href="{{ route('projects.surveys.index', $id) }}" class='btn btn-default btn-sm'>
                        <i class="glyphicon glyphicon-eye-open"></i> {!! trans('messages.list_incidents') !!}
                    </a>
                @else
                    <a href="{{ route('projects.surveys.index', $id) }}" class='btn btn-default btn-sm'>
                        <i class="glyphicon glyphicon-eye-open"></i> {!! trans('messages.list_samples') !!}
                    </a>
                @endif
                {{--<div class="btn-group">--}}
                    {{--<a href="{{ route('projects.smslog', $id) }}" class='btn btn-default btn-sm'>--}}
                        {{--<i class="fa fa-envelope"></i> {!! trans('messages.smslog') !!}--}}
                    {{--</a>--}}
                {{--</div>--}}
                @if(Auth::user()->role->level > 8)
                    <a href="{{ route('projects.edit', $id) }}" class='btn btn-default btn-sm'>
                        <i class="glyphicon glyphicon-edit"></i> {!! trans('messages.edit') !!}
                    </a>
                @endif
            </div>
        </div>

        <div class="row">
            @if(Auth::user()->role->level >= 7)
                <div class="btn-group">
                    <a href="{{ route('projects.analysis', $id) }}" class='btn btn-default btn-sm'>
                        <i class="fa fa-pie-chart"></i> {!! trans('messages.analysis') !!}
                    </a>
                </div>
            @endif
            @if(Auth::user()->role->level > 5)


            @endif

        </div>
    </div>
    <div class="col-sm-4 text-center">
        <div class="row">

            @if(Auth::user()->role->level >= 7)
                <div class="btn-group">
                    <a href="{{ route('projects.response.filter', [$id, $response_filter]) }}" class='btn btn-default btn-sm'>
                        <i class="glyphicon glyphicon-equalizer"></i> {!! trans('messages.response') !!}
                    </a>
                    @if(config('sms.double_entry'))
                        <a href="{{ route('projects.response.filter', [$id, $response_filter, 'double']) }}"
                           class='btn btn-default btn-sm'>
                            <i class="glyphicon glyphicon-transfer"></i> {!! trans('messages.double_entry') !!}
                        </a>
                    @endif
                </div>
            @endif
        </div>
        <div class="row">
            @if(Auth::user()->role->level >= 7)
                @if(config('sms.double_entry'))
                    <a href="{{ route('projects.response.double', [$id]) }}" class='btn btn-default btn-sm'>
                        <i class="glyphicon glyphicon-open"></i> {!! trans('messages.check') !!} <i
                                class="glyphicon glyphicon-open"></i>
                    </a>
                @endif
            @endif
        </div>
    </div>

    <div class="col-sm-4">

        @if(Auth::user()->role->level > 7)
            <div class="btn-group">

                {!! Form::open(['route' => ['translate', $id], 'method' => 'post', 'class' => 'form-inline translation']) !!}
                <div class="input-group">
                    <input type="text" name="columns[project]" class="form-control"
                           placeholder="{!! trans('messages.add_translation') !!}"
                           @if(!empty($project_trans))
                           value="{!! $project_trans !!}"
                            @endif>
                    <input type="hidden" name="model" value="project">
                    <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">{!! trans('messages.save') !!}</button>
                </span>

                </div><!-- /input-group -->
                {!! Form::close() !!}



                <a href="{{ route('locationMetas.edit', $id) }}" class='btn btn-default btn-sm'>
                    <i class="glyphicon glyphicon-edit"></i>Edit Locations
                </a>


                {!! Form::open(['route' => ['projects.destroy', $id], 'method' => 'delete', 'class' => 'from-inline']) !!}

                {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
                    'type' => 'submit',
                    'class' => 'btn btn-danger btn-sm',
                    'onclick' => "return confirm('".trans('messages.are_you_sure')."')"
                ]) !!}

                {!! Form::close() !!}
            </div>
        @endif

    </div>
</div>

resources/views/projects/logicmodal.blade.php
<div class="modal fade" id="logicModal" tabindex="-1" role="dialog" aria-labelledby="logicModalLabel">
    {!! Form::open(['route' => ['projects.logic', $project->id], 'method' => 'post', 'class' => 'addlogic', 'id' => 'logicModalForm']) !!}
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="logicModalLabel">Logic</h4>
            </div>

            <div class="modal-body">
                <div class="row">

                    @include('projects.logicfields')

                </div>
                <div class="row">
                    <div id="fb-editor" class="col-xs-12"></div>
                </div>
            </div>
            <div class="modal-footer">
                <span id="ajaxMesg" class="hidden"></span>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                {!! Form::submit('Save', ['class' => 'btn btn-primary', 'id' => 'saveLogics']) !!}
            </div>

        </div>
    </div>
    {!! Form::close() !!}
</div>