routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
 */

Route::get('/', function () {
    if (Auth::check()) {
        if (Auth::user()->role->role_name == 'trainer') {
            return redirect('smsLogs');
        } else {
            return redirect('projects');
        }
    } else {
        return redirect('projects');
    }

});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::group(['prefix' => 'projects/{project}'], function () {
    Route::match(['get', 'post'], '/response/{filter}/{type?}', ['as' => 'projects.response.filter', 'uses' => 'SurveyResultsController@responseRateSample']);
    Route::match(['get', 'post'], '/double', ['as' => 'projects.response.double', 'uses' => 'SurveyResultsController@responseRateDouble']);
    Route::match(['get', 'post'], '/useorigin/{survey_id}/{column}', ['as' => 'projects.response.origin.use', 'uses' => 'SurveyResultsController@originUse']);
    Route::match(['get', 'post'], '/usedouble/{survey_id}/{column}', ['as' => 'projects.response.double.use', 'uses' => 'SurveyResultsController@doubleUse']);
    Route::get('/search/sample', ['as' => 'projects.sample.search', 'uses' => 'ProjectController@search']);
    Route::get('/sampledata/{sampledata}/form/{formid}', ['as' => 'projects.incident.create', 'uses' => 'ProjectController@addIncident']);
    Route::get('/analysis', ['as' => 'projects.analysis', 'uses' => 'SurveyResultsController@analysis']);
    Route::match(['get','post'],'/smslog', ['as' => 'projects.smslog', 'uses' => 'ProjectController@smslog']);
    Route::get('/export', ['as' => 'projects.export', 'uses' => 'ProjectController@export']);
    Route::post('/import', ['as' => 'projects.import', 'uses' => 'ProjectController@import']);
    Route::get('/create-views', ['as' => 'projects.createviews', 'uses' => 'ProjectController@createAllViews']);
    Route::post('/trainingmode', ['as' => 'projects.trainingmode', 'uses' => 'ProjectController@trainingmode']);
    Route::post('/addlogic', ['as' => 'projects.logic', 'uses' => 'ProjectController@addLogic']);
    Route::post('/upload', ['as' => 'projects.upload.samples', 'uses' => 'ProjectController@uploadSamples']);
    Route::match(['get','post'],'/getcsv', ['as' => 'projects.getcsv', 'uses' => 'API\SmsAPIController@getcsv']);
    Route::get('/channel-rate', ['as' => 'projects.channel.rates', 'uses' => 'ProjectController@channelRates']);

    Route::get('location-metas/show-structure', ['as' => 'location-metas.show-structure', 'uses' => 'LocationMetaController@editStructure']);

    Route::match(['post','patch'],'location-metas/edit-structure', ['as' => 'location-metas.edit-structure', 'uses' => 'LocationMetaController@createOrUpdateStructure']);

    Route::resource('sample-details', 'SampleDetailsController');
});

Route::group(['prefix' => 'projects/{project}/surveys'], function () {

    Route::match(['get', 'post'], '/{sample_type?}', ['as' => 'projects.surveys.index', 'uses' => 'SurveyResultsController@index']);

    Route::get('/{result}/create/{form_id?}/{sample_type?}', ['as' => 'projects.surveys.create', 'uses' => 'SurveyResultsController@create']);

    Route::post('/{result}/save/{form_id?}/{sample_type?}', ['as' => 'projects.surveys.save', 'uses' => 'SurveyResultsController@save']);

    Route::get('/{result}', ['as' => 'projects.surveys.show', 'uses' => 'SurveyResultsController@show']);

    // Route::get('/{sample_id}/edit', ['as' => 'projects.surveys.edit', 'uses' => 'SurveyResultsController@edit']);

    Route::match(['put', 'patch'], '/{result}', ['as' => 'projects.surveys.update', 'uses' => 'SurveyResultsController@update']);

    Route::delete('/{result}', ['as' => 'projects.surveys.destroy', 'uses' => 'SurveyResultsController@destroy']);

});

Route::post('projects/{project}/dbcreate', ['as' => 'projects.dbcreate', 'uses' => ProjectController::class . '@dbcreate']);

Route::get('projects/sort/{project}', ['as' => 'projects.sort', 'uses' => ProjectController::class . '@sort']);

Route::get('projects/migrate', ['as' => 'projects.migrate', 'uses' => ProjectController::class . '@migrate']);

Route::post('projects/import', ['as' => 'projects.import', 'uses' => ProjectController::class . '@import']);


Route::resource('projects', 'ProjectController');

Route::post('questions', ['as' => 'questions.store', 'uses' => QuestionController::class . '@store']);

Route::post('questions/sort', ['as' => 'questions.sort', 'uses' => QuestionController::class . '@sort']);

Route::match(['put', 'patch'], 'questions/{question}', ['as' => 'questions.update', 'uses' => QuestionController::class . '@update']);

Route::delete('questions/{question}', ['as' => 'questions.destroy', 'uses' => QuestionController::class . '@destroy']);

//Route::resource('questions', 'QuestionController');

Route::resource('smsLogs', 'SmsLogController');

Route::match(['get','post'], 'smslogs', ['as' => 'smsLogs.index', 'uses' => 'SmsLogController@index']);

Route::post('translate/{id}', ['as' => 'translate', 'uses' => 'SettingController@translate']);

Route::post('settings/save', ['as' => 'settings.save', 'uses' => 'SettingController@save']);

Route::resource('settings', 'SettingController');

Route::post('sample/import', ['as' => 'sample.import', 'uses' => 'SampleDataController@import']);

Route::resource('sampleDatas', 'SampleDataController');

Route::resource('users', 'UserController');

Route::resource('roles', 'RoleController');

Route::resource('projectPhones', 'ProjectPhoneController');

Route::resource('observers', 'ObserverController');

Route::resource('logicalChecks', 'LogicalCheckController');


Route::resource('location-metas', 'LocationMetaController');

Route::post('translations/import',['as' => 'translations.import', 'uses' => 'TranslationController@import']);

Route::resource('translations', 'TranslationController');

app/Models/ProjectPhone.php
<?php

namespace App\Models;

use Eloquent as Model;

/**
 * Class ProjectPhone
 * @package App\Models
 * @version April 28, 2017, 9:36 pm UTC
 */
class ProjectPhone extends Model
{

    public $table = 'project_phones';

    public $fillable = [
        'phone',
        'project_id',
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'phone' => 'string',
        'project_id' => 'integer',
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [

    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function project()
    {
        return $this->belongsTo(Project::class);
    }
}

app/Http/Controllers/ProjectPhoneController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\ProjectPhoneDataTable;
use App\Http\Controllers\AppBaseController;
use App\Http\Requests\CreateProjectPhoneRequest;
use App\Http\Requests\UpdateProjectPhoneRequest;
use App\Models\Project;
use App\Repositories\ProjectPhoneRepository;
use Flash;
use Response;

class ProjectPhoneController extends AppBaseController
{
    /** @var  ProjectPhoneRepository */
    private $projectPhoneRepository;

    public function __construct(ProjectPhoneRepository $projectPhoneRepo)
    {
        $this->projectPhoneRepository = $projectPhoneRepo;
    }

    /**
     * Display a listing of the ProjectPhone.
     *
     * @param ProjectPhoneDataTable $projectPhoneDataTable
     * @return Response
     */
    public function index(ProjectPhoneDataTable $projectPhoneDataTable)
    {
        return $projectPhoneDataTable->render('project_phones.index');
    }

    /**
     * Show the form for creating a new ProjectPhone.
     *
     * @return Response
     */
    public function create()
    {
        $projects = Project::pluck('project', 'id');
        return view('project_phones.create')->with('projects', $projects);
    }

    /**
     * Store a newly created ProjectPhone in storage.
     *
     * @param CreateProjectPhoneRequest $request
     *
     * @return Response
     */
    public function store(CreateProjectPhoneRequest $request)
    {
        $input = $request->all();

        $projectPhone = $this->projectPhoneRepository->create($input);

        Flash::success('Project Phone saved successfully.');

        return redirect(route('projectPhones.index'));
    }

    /**
     * Display the specified ProjectPhone.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $projectPhone = $this->projectPhoneRepository->findWithoutFail($id);

        if (empty($projectPhone)) {
            Flash::error('Project Phone not found');

            return redirect(route('projectPhones.index'));
        }

        return view('project_phones.show')->with('projectPhone', $projectPhone);
    }

    /**
     * Show the form for editing the specified ProjectPhone.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $projectPhone = $this->projectPhoneRepository->findWithoutFail($id);

        if (empty($projectPhone)) {
            Flash::error('Project Phone not found');

            return redirect(route('projectPhones.index'));
        }

        $projects = Project::pluck('project', 'id');

        return view('project_phones.edit')->with('projectPhone', $projectPhone)->with('projects', $projects);
    }

    /**
     * Update the specified ProjectPhone in storage.
     *
     * @param  int              $id
     * @param UpdateProjectPhoneRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateProjectPhoneRequest $request)
    {
        $projectPhone = $this->projectPhoneRepository->findWithoutFail($id);

        if (empty($projectPhone)) {
            Flash::error('Project Phone not found');

            return redirect(route('projectPhones.index'));
        }

        $projectPhone = $this->projectPhoneRepository->update($request->all(), $id);

        Flash::success('Project Phone updated successfully.');

        return redirect(route('projectPhones.index'));
    }

    /**
     * Remove the specified ProjectPhone from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $projectPhone = $this->projectPhoneRepository->findWithoutFail($id);

        if (empty($projectPhone)) {
            Flash::error('Project Phone not found');

            return redirect(route('projectPhones.index'));
        }

        $this->projectPhoneRepository->delete($id);

        Flash::success('Project Phone deleted successfully.');

        return redirect(route('projectPhones.index'));
    }
}

resources/views/project_phones/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Project Phone
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'projectPhones.store']) !!}

                        @include('project_phones.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/project_phones/datatables_actions.blade.php
{!! Form::open(['route' => ['projectPhones.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('projectPhones.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('projectPhones.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/project_phones/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Project Phone
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($projectPhone, ['route' => ['projectPhones.update', $projectPhone->id], 'method' => 'patch']) !!}

                        @include('project_phones.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/project_phones/fields.blade.php
<!-- Phone Field -->
<div class="form-group col-sm-6">
    {!! Form::label('phone', 'Phone:') !!}
    {!! Form::text('phone', null, ['class' => 'form-control']) !!}
</div>

<!-- Project Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('project_id', 'Project Id:') !!}
    {!! Form::select('project_id', $projects, null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('projectPhones.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/project_phones/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Project Phones</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('projectPhones.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('project_phones.table')
            </div>
        </div>
    </div>
@endsection

resources/views/project_phones/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Project Phone
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('project_phones.show_fields')
                    <a href="{!! route('projectPhones.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/project_phones/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $projectPhone->id !!}</p>
</div>

<!-- Phone Field -->
<div class="form-group">
    {!! Form::label('phone', 'Phone:') !!}
    <p>{!! $projectPhone->phone !!}</p>
</div>

<!-- Project Id Field -->
<div class="form-group">
    {!! Form::label('project_id', 'Project Id:') !!}
    <p>{!! $projectPhone->project_id !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $projectPhone->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $projectPhone->updated_at !!}</p>
</div>

resources/views/project_phones/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection