routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
 */

Route::get('/', function () {
    if (Auth::check()) {
        if (Auth::user()->role->role_name == 'trainer') {
            return redirect('smsLogs');
        } else {
            return redirect('projects');
        }
    } else {
        return redirect('projects');
    }

});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::group(['prefix' => 'projects/{project}'], function () {
    Route::match(['get', 'post'], '/response/{filter}/{type?}', ['as' => 'projects.response.filter', 'uses' => 'SurveyResultsController@responseRateSample']);
    Route::match(['get', 'post'], '/double', ['as' => 'projects.response.double', 'uses' => 'SurveyResultsController@responseRateDouble']);
    Route::match(['get', 'post'], '/useorigin/{survey_id}/{column}', ['as' => 'projects.response.origin.use', 'uses' => 'SurveyResultsController@originUse']);
    Route::match(['get', 'post'], '/usedouble/{survey_id}/{column}', ['as' => 'projects.response.double.use', 'uses' => 'SurveyResultsController@doubleUse']);
    Route::get('/search/sample', ['as' => 'projects.sample.search', 'uses' => 'ProjectController@search']);
    Route::get('/sampledata/{sampledata}/form/{formid}', ['as' => 'projects.incident.create', 'uses' => 'ProjectController@addIncident']);
    Route::get('/analysis', ['as' => 'projects.analysis', 'uses' => 'SurveyResultsController@analysis']);
    Route::match(['get','post'],'/smslog', ['as' => 'projects.smslog', 'uses' => 'ProjectController@smslog']);
    Route::get('/export', ['as' => 'projects.export', 'uses' => 'ProjectController@export']);
    Route::post('/import', ['as' => 'projects.import', 'uses' => 'ProjectController@import']);
    Route::get('/create-views', ['as' => 'projects.createviews', 'uses' => 'ProjectController@createAllViews']);
    Route::post('/trainingmode', ['as' => 'projects.trainingmode', 'uses' => 'ProjectController@trainingmode']);
    Route::post('/addlogic', ['as' => 'projects.logic', 'uses' => 'ProjectController@addLogic']);
    Route::post('/upload', ['as' => 'projects.upload.samples', 'uses' => 'ProjectController@uploadSamples']);
    Route::match(['get','post'],'/getcsv', ['as' => 'projects.getcsv', 'uses' => 'API\SmsAPIController@getcsv']);
    Route::get('/channel-rate', ['as' => 'projects.channel.rates', 'uses' => 'ProjectController@channelRates']);

    Route::get('location-metas/show-structure', ['as' => 'location-metas.show-structure', 'uses' => 'LocationMetaController@editStructure']);

    Route::match(['post','patch'],'location-metas/edit-structure', ['as' => 'location-metas.edit-structure', 'uses' => 'LocationMetaController@createOrUpdateStructure']);

    Route::resource('sample-details', 'SampleDetailsController');
});

Route::group(['prefix' => 'projects/{project}/surveys'], function () {

    Route::match(['get', 'post'], '/{sample_type?}', ['as' => 'projects.surveys.index', 'uses' => 'SurveyResultsController@index']);

    Route::get('/{result}/create/{form_id?}/{sample_type?}', ['as' => 'projects.surveys.create', 'uses' => 'SurveyResultsController@create']);

    Route::post('/{result}/save/{form_id?}/{sample_type?}', ['as' => 'projects.surveys.save', 'uses' => 'SurveyResultsController@save']);

    Route::get('/{result}', ['as' => 'projects.surveys.show', 'uses' => 'SurveyResultsController@show']);

    // Route::get('/{sample_id}/edit', ['as' => 'projects.surveys.edit', 'uses' => 'SurveyResultsController@edit']);

    Route::match(['put', 'patch'], '/{result}', ['as' => 'projects.surveys.update', 'uses' => 'SurveyResultsController@update']);

    Route::delete('/{result}', ['as' => 'projects.surveys.destroy', 'uses' => 'SurveyResultsController@destroy']);

});

Route::post('projects/{project}/dbcreate', ['as' => 'projects.dbcreate', 'uses' => ProjectController::class . '@dbcreate']);

Route::get('projects/sort/{project}', ['as' => 'projects.sort', 'uses' => ProjectController::class . '@sort']);

Route::get('projects/migrate', ['as' => 'projects.migrate', 'uses' => ProjectController::class . '@migrate']);

Route::post('projects/import', ['as' => 'projects.import', 'uses' => ProjectController::class . '@import']);


Route::resource('projects', 'ProjectController');

Route::post('questions', ['as' => 'questions.store', 'uses' => QuestionController::class . '@store']);

Route::post('questions/sort', ['as' => 'questions.sort', 'uses' => QuestionController::class . '@sort']);

Route::match(['put', 'patch'], 'questions/{question}', ['as' => 'questions.update', 'uses' => QuestionController::class . '@update']);

Route::delete('questions/{question}', ['as' => 'questions.destroy', 'uses' => QuestionController::class . '@destroy']);

//Route::resource('questions', 'QuestionController');

Route::resource('smsLogs', 'SmsLogController');

Route::match(['get','post'], 'smslogs', ['as' => 'smsLogs.index', 'uses' => 'SmsLogController@index']);

Route::post('translate/{id}', ['as' => 'translate', 'uses' => 'SettingController@translate']);

Route::post('settings/save', ['as' => 'settings.save', 'uses' => 'SettingController@save']);

Route::resource('settings', 'SettingController');

Route::post('sample/import', ['as' => 'sample.import', 'uses' => 'SampleDataController@import']);

Route::resource('sampleDatas', 'SampleDataController');

Route::resource('users', 'UserController');

Route::resource('roles', 'RoleController');

Route::resource('projectPhones', 'ProjectPhoneController');

Route::resource('observers', 'ObserverController');

Route::resource('logicalChecks', 'LogicalCheckController');


Route::resource('location-metas', 'LocationMetaController');

Route::post('translations/import',['as' => 'translations.import', 'uses' => 'TranslationController@import']);

Route::resource('translations', 'TranslationController');

app/Models/SampleData.php
<?php

namespace App\Models;

use Eloquent as Model;

/**
 * Class SampleData
 * @package App\Models
 * @version December 30, 2016, 1:04 pm UTC
 */
class SampleData extends Model
{

    public $table = 'sample_datas';

    public $timestamps = false;

    public $incrementing = false;

    public $fillable = [

    ];

    public static $export = [
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [

    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [

    ];

    public function samples()
    {
        return $this->hasMany(Sample::class, 'sample_data_id');
    }

    public function observers()
    {
        return $this->hasMany(Observer::class, 'sample_id');
    }

    public function projects()
    {
        return $this->belongsToMany(Projects::class, 'samples', 'sample_data_id', 'project_id');
    }

    public function getSampleByCode($code, $table)
    {
        $this->setTable($table);
        return $this->find($code);
    }

    /**
     * Determine if a get mutator exists for an attribute.
     *
     * @param  string  $key
     * @return bool
     */
    public function hasGetMutator($key)
    {

        preg_match('/get(.*)Attribute/', $key, $matches);

        //return method_exists($this, 'get'.Str::studly($key).'Attribute');
        return true;
    }

    public function __call($method, $parameters)
    {
        if (in_array($method, ['increment', 'decrement'])) {
            return $this->$method(...$parameters);
        }

        if(preg_match('/get(.*)Attribute/', $method, $matches)) {
            if (\App::isLocale(config('app.locale'))) {
                return $parameters[0];
            } else {
                return trans('location.' . str_dbcolumn($parameters[0]));
            }
        }

        return $this->newQuery()->$method(...$parameters);
    }

    /*
     * Need to sanitize data
     */

    function insertOrUpdate(array $rows, $table){
        //$table = \DB::getTablePrefix().with(new self)->getTable();

        $first = reset($rows);

        $columns = implode( ',',
            array_map( function( $value ) { return "$value"; } , array_keys($first) )
        );

        $values = implode( ',', array_map( function( $row ) {
                return '('.implode( ',',
                        array_map( function( $value ) { return '"'.str_replace('"', '""', $value).'"'; } , $row )
                    ).')';
            } , $rows )
        );

        $updates = implode( ',',
            array_map( function( $value ) { return "$value = VALUES($value)"; } , array_keys($first) )
        );

        $sql = "INSERT INTO {$table}({$columns}) VALUES {$values} ON DUPLICATE KEY UPDATE {$updates}";

        return \DB::statement( $sql );
    }

}

app/Http/Controllers/SampleDataController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\SampleDataDataTable;
use App\Http\Requests\CreateSampleDataRequest;
use App\Http\Requests\UpdateSampleDataRequest;
use App\Models\Observer;
use App\Models\SampleData;
use App\Repositories\SampleDataRepository;
use Flash;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;
use Response;

class SampleDataController extends AppBaseController
{
    /** @var  SampleDataRepository */
    private $sampleDataRepository;

    public function __construct(SampleDataRepository $sampleDataRepo)
    {
        $this->middleware('auth');
        $this->sampleDataRepository = $sampleDataRepo;
    }

    /**
     * Display a listing of the SampleData.
     *
     * @param SampleDataDataTable $sampleDataDataTable
     * @return Response
     */
    public function index(SampleDataDataTable $sampleDataDataTable)
    {
        return $sampleDataDataTable->render('sample_datas.index');
    }

    /**
     * Show the form for creating a new SampleData.
     *
     * @return Response
     */
    public function create()
    {
        return view('sample_datas.create');
    }

    /**
     * Store a newly created SampleData in storage.
     *
     * @param CreateSampleDataRequest $request
     *
     * @return Response
     */
    public function store(CreateSampleDataRequest $request)
    {
        $input = $request->all();

        $sampleData = $this->sampleDataRepository->create($input);

        Flash::success('Sample Data saved successfully.');

        return redirect(route('sampleDatas.index'));
    }

    /**
     * Display the specified SampleData.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $sampleData = $this->sampleDataRepository->findWithoutFail($id);

        if (empty($sampleData)) {
            Flash::error('Sample Data not found');

            return redirect(route('sampleDatas.index'));
        }

        return view('sample_datas.show')->with('sampleData', $sampleData);
    }

    /**
     * Show the form for editing the specified SampleData.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $sampleData = $this->sampleDataRepository->findWithoutFail($id);

        if (empty($sampleData)) {
            Flash::error('Sample Data not found');

            return redirect(route('sampleDatas.index'));
        }

        return view('sample_datas.edit')->with('sampleData', $sampleData);
    }

    /**
     * Update the specified SampleData in storage.
     *
     * @param  int $id
     * @param UpdateSampleDataRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateSampleDataRequest $request)
    {
        $sampleData = $this->sampleDataRepository->findWithoutFail($id);

        if (empty($sampleData)) {
            Flash::error('Sample Data not found');

            return redirect(route('sampleDatas.index'));
        }

        $sampleData = $this->sampleDataRepository->update($request->all(), $id);

        Flash::success('Sample Data updated successfully.');

        return redirect(route('sampleDatas.index'));
    }

    /**
     * Remove the specified SampleData from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $sampleData = $this->sampleDataRepository->findWithoutFail($id);

        if (empty($sampleData)) {
            Flash::error('Sample Data not found');

            return redirect(route('sampleDatas.index'));
        }

        $this->sampleDataRepository->delete($id);

        Flash::success('Sample Data deleted successfully.');

        return redirect(route('sampleDatas.index'));
    }

    public function import(Request $request)
    {
        $file = $request->file('samplefile');
        $type = $request->only('type');
        $group = $request->only('dbgroup');
        Excel::load($file, function ($reader) use ($type, $group) {
            $reader->each(function ($row) use ($type, $group) {
                $location_default = [
                    'location_code' => [
                        'title' => 'Location Code',
                        'primary' => true,
                        'foreign' => false // foreign key
                    ]
                ];
                $locations = array_merge($location_default, config('samples.locations'));

                $locations_rows = [];
                $locations_attrs = [];
                $observers_attrs = [];
                foreach($locations as $location => $options) {
                    $locations_rows[$location] = (string) ($row->{$location}) ? $row->{$location} : null;
                    if($location && array_key_exists('primary', $options) && $options['primary']) {
                        $locations_attrs[$location] = (string) $row->{$location};
                    }

                    if($location && array_key_exists('foreign', $options) && $options['foreign']) {
                        $observers_attrs[$location] = (string) $row->{$location};
                    }
                }

                if ($row->location_code) {

                    $location_data = SampleData::updateOrCreate($locations_attrs, $locations_rows);
                    if($location_data->id) {
                        $observer_default = [
                            'code' => [
                                'title' => 'Observer Code',
                                'primary' => true
                            ]
                        ];

                        $observers = array_merge($observer_default, config('samples.observers'));

                        $observers_rows = [];

                        $observers_attrs['sample_id'] = ($location_data->id) ? $location_data->id : null;

                        foreach ($observers as $observer => $options) {
                            if($observer && array_key_exists('type', $options) && $options['type']) {
                                switch($options['type']) {
                                    case 'date':
                                        $observers_rows[$observer] = ($row->{$observer}) ? date('Y-m-d', strtotime($row->{$observer})) : null;
                                        break;
                                    default:
                                        $observers_rows[$observer] = ($row->{$observer}) ? $row->{$observer} : null;
                                        break;
                                }

                            } elseif($observer && array_key_exists('notnull', $options) && $options['notnull']) {
                                $observers_rows[$observer] = ($row->{$observer}) ? $row->{$observer} : 'N/A';
                            } else {
                                $observers_rows[$observer] = ($row->{$observer}) ? $row->{$observer} : null;
                            }

                            if (config('samples.unique') == 'observer') {
                                $observers_rows['code'] = $row->location_code . '-' . $row->code;
                            }
                        }

                        $observer = Observer::updateOrCreate($observers_attrs, $observers_rows);

                        $location_data->save();
                    }
                }
            });
        });

        Flash::success($file . ' Data imported successfully.');
        return redirect()->back();
    }

}

resources/views/sample_datas/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Sample Data
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'sampleDatas.store']) !!}

                        @include('sample_datas.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/sample_datas/datatables_actions.blade.php
{!! Form::open(['route' => ['sampleDatas.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('sampleDatas.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('sampleDatas.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('".trans('messages.are_you_sure')."')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/sample_datas/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Sample Data
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($sampleData, ['route' => ['sampleDatas.update', $sampleData->id], 'method' => 'patch']) !!}

                        @include('sample_datas.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/sample_datas/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Sample Datas</h1>
        <h1 class="pull-right">
            <!-- button data-toggle="modal" data-target="#translateModal" class="btn btn-primary" style="margin-top: -10px;margin-bottom: 5px; margin-right:5px;">{!! trans('messages.importTranslation') !!}</button-->

            <button data-toggle="modal" data-target="#importModal" class="btn btn-primary" style="margin-top: -10px;margin-bottom: 5px; margin-right:5px;">{!! trans('messages.import') !!}</button>

           <!-- a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('sampleDatas.create') !!}">{!! trans('messages.add_new') !!}</a-->
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('sample_datas.table')
            </div>
        </div>
    </div>
<div class="modal fade" id="importModal" tabindex="-1" role="dialog" aria-labelledby="importModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
    {!! Form::open(['route' => 'sample.import', 'id' => 'importModalForm', 'method' => 'POST', 'files' => true, 'class' => 'form-inline']) !!}
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="importModalLabel">Import Sample Data</h4>
      </div>

      <div class="modal-body">
      <h4> Your CSV file should include following columns (ID Code is mandatory)</h4>
      <table class="table table-striped">
          <tr>
              <th>ID Code</th>
              <th>State</th>
              <th>District</th>
              <th>Township</th>
              <th>Village_Tract</th>
              <th>Village</th>
              <th>Name</th>
              <th>N.R.C No.</th>
              <th>Gender</th>
              <th>Date of Birth</th>
              <th>Edu Background</th>
            </tr>
            <tr>
              <th>Father</th>
              <th>Mother</th>
              <th>Ethinicity</th>
              <th>Language</th>
              <th>Current occupation</th>
              <th>Phone no. (1)</th>
              <th>Phone no. (2)</th>
              <th>Address</th>
              <th>Bank Information</th>
              <th>Mobile Provider</th>
          </tr>
      </table>
      <h4> Data type and Data group will be used when building form and generating sample list for data entry.</h4>
        <div class="input-group">
            <span class="input-group-addon" id="datatype">Data Type: </span>
            {!! Form::select('type', ['enumerator' => 'Enumerator', 'spotchecker' => 'Spot Checker', 'location' => 'Location', 'voter' => 'Voter'], null, ['class' => 'form-control', 'aria-describedby' => 'datatype']) !!}
        </div>
         <div class="input-group">
            <span class="input-group-addon" id="dbgroup">Data Group: </span>
            {!! Form::select('dbgroup', ['1' => 'Group 1','2' => 'Group 2','3' => 'Group 3','4' => 'Group 4','5' => 'Group 5'], null, ['class' => 'form-control', 'aria-describedby' => 'dbgroup']) !!}
        </div>
        <div class="input-group">
            <span class="btn btn-primary btn-file" id="file">
                <label for="upload" id="file-label">Browse File</label>
                {!! Form::file('samplefile', ['aria-describedby' => 'file', 'id'=>'upload']); !!}
            </span>
        </div>
      </div>
      <div class="modal-footer">
        <span id="ajaxMesg" class="hidden"></span>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        {!! Form::submit('import', ['class' => 'btn btn-primary', 'id' => 'importData']) !!}
      </div>
      {!! Form::close() !!}
    </div>
  </div>
</div>

<div class="modal fade" id="translateModal" tabindex="-1" role="dialog" aria-labelledby="translateModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
    {!! Form::open(['route' => 'sample.importTranslation', 'id' => 'translateModalForm', 'method' => 'POST', 'files' => true, 'class' => 'form-inline']) !!}
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="importModalLabel">Import Sample Data</h4>
      </div>

      <div class="modal-body">
      <h4> Your CSV file should include following columns (ID Code is mandatory)</h4>
      <table class="table table-striped">
          <tr>
              <th>ID Code</th>
              <th>State</th>
              <th>District</th>
              <th>Township</th>
              <th>Village_Tract</th>
              <th>Village</th>
              <th>Name</th>
              <th>N.R.C No.</th>
              <th>Gender</th>
              <th>Date of Birth</th>
              <th>Edu Background</th>
            </tr>
            <tr>
              <th>Father</th>
              <th>Mother</th>
              <th>Ethinicity</th>
              <th>Language</th>
              <th>Current occupation</th>
              <th>Phone no. (1)</th>
              <th>Phone no. (2)</th>
              <th>Address</th>
              <th>Bank Information</th>
              <th>Mobile Provider</th>
          </tr>
      </table>
      <h4> Data type and Data group will be used when building form and generating sample list for data entry.</h4>
        <div class="input-group">
            <span class="input-group-addon" id="datatype">Data Type: </span>
            {!! Form::select('type', ['enumerator' => 'Enumerator', 'spotchecker' => 'Spot Checker', 'location' => 'Location', 'voter' => 'Voter'], null, ['class' => 'form-control', 'aria-describedby' => 'datatype']) !!}
        </div>
         <div class="input-group">
            <span class="input-group-addon" id="dbgroup">Data Group: </span>
            {!! Form::select('dbgroup', ['1' => 'Group 1','2' => 'Group 2','3' => 'Group 3','4' => 'Group 4','5' => 'Group 5'], null, ['class' => 'form-control', 'aria-describedby' => 'dbgroup']) !!}
        </div>
        <div class="input-group">
            <span class="btn btn-primary btn-file" id="file">
                <label for="upload" id="translate-file-label">Browse File</label>
                {!! Form::file('samplefile', ['aria-describedby' => 'file', 'id'=>'transupload']); !!}
            </span>
        </div>
      </div>
      <div class="modal-footer">
        <span id="ajaxMesg" class="hidden"></span>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        {!! Form::submit('import', ['class' => 'btn btn-primary', 'id' => 'importData']) !!}
      </div>
      {!! Form::close() !!}
    </div>
  </div>
</div>
@endsection
<!-- https://www.abeautifulsite.net/whipping-file-inputs-into-shape-with-bootstrap-3 -->
@push('before-head-end')
<style type="text/css">
label#file-label {
    margin-bottom: 0px !important;
}
.btn-file {
    position: relative;
    overflow: hidden;
}
.btn-file input[type=file] {
    position: absolute;
    top: 0;
    right: 0;
    min-width: 100%;
    min-height: 100%;
    font-size: 100px;
    text-align: right;
    filter: alpha(opacity=0);
    opacity: 0;
    outline: none;
    background: white;
    cursor: inherit;
    display: block;
}
</style>
@endpush
@push('before-body-end')
<script type="text/javascript">
$(document).ready(function(){
    $('#importModal').on('shown.bs.modal', function(event) {
            $('#upload').on('change',function(e){
                fileName = e.target.value.split( '\\' ).pop();
                $('#file-label').html(fileName);
            });
    });

    $('#translateModal').on('shown.bs.modal', function(event) {
            $('#transupload').on('change',function(e){
                fileName = e.target.value.split( '\\' ).pop();
                $('#translate-file-label').html(fileName);
            });
    });
});
</script>
@endpush

resources/views/sample_datas/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Sample Data
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('sample_datas.show_fields')
                    <a href="{!! route('sampleDatas.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/sample_datas/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $sampleData->id !!}</p>
</div>

<!-- Idcode Field -->
<div class="form-group">
    {!! Form::label('idcode', 'Idcode:') !!}
    <p>{!! $sampleData->idcode !!}</p>
</div>

<!-- Type Field -->
<div class="form-group">
    {!! Form::label('type', 'Type:') !!}
    <p>{!! $sampleData->type !!}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $sampleData->name !!}</p>
</div>

<!-- Gender Field -->
<div class="form-group">
    {!! Form::label('gender', 'Gender:') !!}
    <p>{!! $sampleData->gender !!}</p>
</div>

<!-- Nrc Id Field -->
<div class="form-group">
    {!! Form::label('nrc_id', 'Nrc Id:') !!}
    <p>{!! $sampleData->nrc_id !!}</p>
</div>

<!-- Dob Field -->
<div class="form-group">
    {!! Form::label('dob', 'Dob:') !!}
    <p>{!! $sampleData->dob !!}</p>
</div>

<!-- Father Field -->
<div class="form-group">
    {!! Form::label('father', 'Father:') !!}
    <p>{!! $sampleData->father !!}</p>
</div>

<!-- Mother Field -->
<div class="form-group">
    {!! Form::label('mother', 'Mother:') !!}
    <p>{!! $sampleData->mother !!}</p>
</div>

<!-- Address Field -->
<div class="form-group">
    {!! Form::label('address', 'Address:') !!}
    <p>{!! $sampleData->address !!}</p>
</div>

<!-- Village Field -->
<div class="form-group">
    {!! Form::label('village', 'Village:') !!}
    <p>{!! $sampleData->village !!}</p>
</div>

<!-- Village Tract Field -->
<div class="form-group">
    {!! Form::label('village_tract', 'Village Tract:') !!}
    <p>{!! $sampleData->village_tract !!}</p>
</div>

<!-- Township Field -->
<div class="form-group">
    {!! Form::label('township', 'Township:') !!}
    <p>{!! $sampleData->township !!}</p>
</div>

<!-- District Field -->
<div class="form-group">
    {!! Form::label('district', 'District:') !!}
    <p>{!! $sampleData->district !!}</p>
</div>

<!-- State Field -->
<div class="form-group">
    {!! Form::label('state', 'State:') !!}
    <p>{!! $sampleData->state !!}</p>
</div>

<!-- Parent Id Field -->
<div class="form-group">
    {!! Form::label('parent_id', 'Parent Id:') !!}
    <p>{!! $sampleData->parent_id !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $sampleData->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $sampleData->updated_at !!}</p>
</div>

resources/views/sample_datas/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection