routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
 */

Route::get('/', function () {
    if (Auth::check()) {
        if (Auth::user()->role->role_name == 'trainer') {
            return redirect('smsLogs');
        } else {
            return redirect('projects');
        }
    } else {
        return redirect('projects');
    }

});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::group(['prefix' => 'projects/{project}'], function () {
    Route::match(['get', 'post'], '/response/{filter}/{type?}', ['as' => 'projects.response.filter', 'uses' => 'SurveyResultsController@responseRateSample']);
    Route::match(['get', 'post'], '/double', ['as' => 'projects.response.double', 'uses' => 'SurveyResultsController@responseRateDouble']);
    Route::match(['get', 'post'], '/useorigin/{survey_id}/{column}', ['as' => 'projects.response.origin.use', 'uses' => 'SurveyResultsController@originUse']);
    Route::match(['get', 'post'], '/usedouble/{survey_id}/{column}', ['as' => 'projects.response.double.use', 'uses' => 'SurveyResultsController@doubleUse']);
    Route::get('/search/sample', ['as' => 'projects.sample.search', 'uses' => 'ProjectController@search']);
    Route::get('/sampledata/{sampledata}/form/{formid}', ['as' => 'projects.incident.create', 'uses' => 'ProjectController@addIncident']);
    Route::get('/analysis', ['as' => 'projects.analysis', 'uses' => 'SurveyResultsController@analysis']);
    Route::match(['get','post'],'/smslog', ['as' => 'projects.smslog', 'uses' => 'ProjectController@smslog']);
    Route::get('/export', ['as' => 'projects.export', 'uses' => 'ProjectController@export']);
    Route::post('/import', ['as' => 'projects.import', 'uses' => 'ProjectController@import']);
    Route::get('/create-views', ['as' => 'projects.createviews', 'uses' => 'ProjectController@createAllViews']);
    Route::post('/trainingmode', ['as' => 'projects.trainingmode', 'uses' => 'ProjectController@trainingmode']);
    Route::post('/addlogic', ['as' => 'projects.logic', 'uses' => 'ProjectController@addLogic']);
    Route::post('/upload', ['as' => 'projects.upload.samples', 'uses' => 'ProjectController@uploadSamples']);
    Route::match(['get','post'],'/getcsv', ['as' => 'projects.getcsv', 'uses' => 'API\SmsAPIController@getcsv']);
    Route::get('/channel-rate', ['as' => 'projects.channel.rates', 'uses' => 'ProjectController@channelRates']);

    Route::get('location-metas/show-structure', ['as' => 'location-metas.show-structure', 'uses' => 'LocationMetaController@editStructure']);

    Route::match(['post','patch'],'location-metas/edit-structure', ['as' => 'location-metas.edit-structure', 'uses' => 'LocationMetaController@createOrUpdateStructure']);

    Route::resource('sample-details', 'SampleDetailsController');
});

Route::group(['prefix' => 'projects/{project}/surveys'], function () {

    Route::match(['get', 'post'], '/{sample_type?}', ['as' => 'projects.surveys.index', 'uses' => 'SurveyResultsController@index']);

    Route::get('/{result}/create/{form_id?}/{sample_type?}', ['as' => 'projects.surveys.create', 'uses' => 'SurveyResultsController@create']);

    Route::post('/{result}/save/{form_id?}/{sample_type?}', ['as' => 'projects.surveys.save', 'uses' => 'SurveyResultsController@save']);

    Route::get('/{result}', ['as' => 'projects.surveys.show', 'uses' => 'SurveyResultsController@show']);

    // Route::get('/{sample_id}/edit', ['as' => 'projects.surveys.edit', 'uses' => 'SurveyResultsController@edit']);

    Route::match(['put', 'patch'], '/{result}', ['as' => 'projects.surveys.update', 'uses' => 'SurveyResultsController@update']);

    Route::delete('/{result}', ['as' => 'projects.surveys.destroy', 'uses' => 'SurveyResultsController@destroy']);

});

Route::post('projects/{project}/dbcreate', ['as' => 'projects.dbcreate', 'uses' => ProjectController::class . '@dbcreate']);

Route::get('projects/sort/{project}', ['as' => 'projects.sort', 'uses' => ProjectController::class . '@sort']);

Route::get('projects/migrate', ['as' => 'projects.migrate', 'uses' => ProjectController::class . '@migrate']);

Route::post('projects/import', ['as' => 'projects.import', 'uses' => ProjectController::class . '@import']);


Route::resource('projects', 'ProjectController');

Route::post('questions', ['as' => 'questions.store', 'uses' => QuestionController::class . '@store']);

Route::post('questions/sort', ['as' => 'questions.sort', 'uses' => QuestionController::class . '@sort']);

Route::match(['put', 'patch'], 'questions/{question}', ['as' => 'questions.update', 'uses' => QuestionController::class . '@update']);

Route::delete('questions/{question}', ['as' => 'questions.destroy', 'uses' => QuestionController::class . '@destroy']);

//Route::resource('questions', 'QuestionController');

Route::resource('smsLogs', 'SmsLogController');

Route::match(['get','post'], 'smslogs', ['as' => 'smsLogs.index', 'uses' => 'SmsLogController@index']);

Route::post('translate/{id}', ['as' => 'translate', 'uses' => 'SettingController@translate']);

Route::post('settings/save', ['as' => 'settings.save', 'uses' => 'SettingController@save']);

Route::resource('settings', 'SettingController');

Route::post('sample/import', ['as' => 'sample.import', 'uses' => 'SampleDataController@import']);

Route::resource('sampleDatas', 'SampleDataController');

Route::resource('users', 'UserController');

Route::resource('roles', 'RoleController');

Route::resource('projectPhones', 'ProjectPhoneController');

Route::resource('observers', 'ObserverController');

Route::resource('logicalChecks', 'LogicalCheckController');


Route::resource('location-metas', 'LocationMetaController');

Route::post('translations/import',['as' => 'translations.import', 'uses' => 'TranslationController@import']);

Route::resource('translations', 'TranslationController');

app/Models/SmsLog.php
<?php

namespace App\Models;

use Eloquent as Model;

/**
 * Class SmsLog
 * @package App\Models
 * @version December 9, 2016, 5:27 pm UTC
 */
class SmsLog extends Model
{

    public $table = 'sms_logs';

    public $incrementing = false;

    public $fillable = [
        'id',
        'service_id',
        'from_number',
        'to_number',
        'name',
        'content',
        'error_message',
        'search_result',
        'phone',
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'string',
        'service_id' => 'string',
        'from_number' => 'string',
        'to_number' => 'string',
        'name' => 'string',
        'content' => 'string',
        'error_message' => 'array',
        'search_result' => 'array',
        'phone' => 'array',
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [

    ];

}

app/Http/Controllers/SmsLogController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\SmsLogDataTable;
use App\Http\Requests\CreateSmsLogRequest;
use App\Http\Requests\UpdateSmsLogRequest;
use App\Models\Project;
use App\Models\SmsLog;
use App\Repositories\SmsLogRepository;
use Flash;
use Response;

class SmsLogController extends AppBaseController
{
    /** @var  SmsLogRepository */
    private $smsLogRepository;

    public function __construct(SmsLogRepository $smsLogRepo)
    {
        $this->middleware('auth');
        $this->smsLogRepository = $smsLogRepo;
    }

    /**
     * Display a listing of the SmsLog.
     *
     * @param SmsLogDataTable $smsLogDataTable
     * @return Response
     */
    public function index(SmsLogDataTable $smsLogDataTable)
    {
        try {
            $this->authorize('index', SmsLog::class);
        } catch (AuthorizationException $e) {
            Flash::error($e->getMessage());
            return redirect()->back();
        }

        $projects = Project::all();
        return $smsLogDataTable->render('sms_logs.index', compact('projects'));
    }

    /**
     * Show the form for creating a new SmsLog.
     *
     * @return Response
     */
    public function create()
    {
        return view('sms_logs.create');
    }

    /**
     * Store a newly created SmsLog in storage.
     *
     * @param CreateSmsLogRequest $request
     *
     * @return Response
     */
    public function store(CreateSmsLogRequest $request)
    {
        $input = $request->all();

        $smsLog = $this->smsLogRepository->create($input);

        Flash::success('Sms Log saved successfully.');

        return redirect(route('smsLogs.index'));
    }

    /**
     * Display the specified SmsLog.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $smsLog = $this->smsLogRepository->findWithoutFail($id);

        if (empty($smsLog)) {
            Flash::error('Sms Log not found');

            return redirect(route('smsLogs.index'));
        }

        return view('sms_logs.show')->with('smsLog', $smsLog);
    }

    /**
     * Show the form for editing the specified SmsLog.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $smsLog = $this->smsLogRepository->findWithoutFail($id);

        if (empty($smsLog)) {
            Flash::error('Sms Log not found');

            return redirect(route('smsLogs.index'));
        }

        return view('sms_logs.edit')->with('smsLog', $smsLog);
    }

    /**
     * Update the specified SmsLog in storage.
     *
     * @param  int $id
     * @param UpdateSmsLogRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateSmsLogRequest $request)
    {
        $smsLog = $this->smsLogRepository->findWithoutFail($id);

        if (empty($smsLog)) {
            Flash::error('Sms Log not found');

            return redirect(route('smsLogs.index'));
        }

        $smsLog = $this->smsLogRepository->update($request->all(), $id);

        Flash::success('Sms Log updated successfully.');

        return redirect(route('smsLogs.index'));
    }

    /**
     * Remove the specified SmsLog from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $smsLog = $this->smsLogRepository->findWithoutFail($id);

        if (empty($smsLog)) {
            Flash::error('Sms Log not found');

            return redirect(route('smsLogs.index'));
        }

        $this->smsLogRepository->delete($id);

        Flash::success('Sms Log deleted successfully.');

        return redirect(route('smsLogs.index'));
    }
}

resources/views/sms_logs/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Sms Log
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'smsLogs.store']) !!}

                        @include('sms_logs.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/sms_logs/datatables_actions.blade.php
{!! Form::open(['route' => ['smsLogs.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('smsLogs.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('smsLogs.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('".trans('messages.are_you_sure')."')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/sms_logs/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Sms Log
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($smsLog, ['route' => ['smsLogs.update', $smsLog->id], 'method' => 'patch']) !!}

                        @include('sms_logs.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/sms_logs/fields.blade.php
<!-- Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('id', 'Id:') !!}
    {!! Form::text('id', null, ['class' => 'form-control']) !!}
</div>

<!-- Service Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('service_id', 'Service Id:') !!}
    {!! Form::text('service_id', null, ['class' => 'form-control']) !!}
</div>

<!-- From Number Field -->
<div class="form-group col-sm-6">
    {!! Form::label('from_number', 'From Number:') !!}
    {!! Form::text('from_number', null, ['class' => 'form-control']) !!}
</div>

<!-- To Number Field -->
<div class="form-group col-sm-6">
    {!! Form::label('to_number', 'To Number:') !!}
    {!! Form::text('to_number', null, ['class' => 'form-control']) !!}
</div>

<!-- Content Field -->
<div class="form-group col-sm-6">
    {!! Form::label('content', 'Content:') !!}
    {!! Form::text('content', null, ['class' => 'form-control']) !!}
</div>

<!-- Error Message Field -->
<div class="form-group col-sm-6">
    {!! Form::label('status_message', 'Error Message:') !!}
    {!! Form::text('status_message', null, ['class' => 'form-control']) !!}
</div>

<!-- Search Result Field -->
<div class="form-group col-sm-6">
    {!! Form::label('search_result', 'Search Result:') !!}
    {!! Form::text('search_result', null, ['class' => 'form-control']) !!}
</div>

<!-- Phone Field -->
<div class="form-group col-sm-6">
    {!! Form::label('phone', 'Phone:') !!}
    {!! Form::text('phone', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('smsLogs.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/sms_logs/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">@if(isset($project)) {!! $project->project !!} @endif Sms Logs</h1>
        <span class="pull-right  form-inline">
            <label for="project" class="control-label">Select Project:</label>
            <select id="project" name="project" class="form-control">
                <option value="{!! route('smsLogs.index') !!}">All</option>
                @foreach($projects as $p)
                    <option value="{!! route('projects.smslog', $p->id) !!}" @if(isset($project) && $p->id === $project->id) selected="selected" @endif>{!! $p->project !!}</option>
                @endforeach
            </select>
        </span>
        <div class="clearfix"></div>
        @if(isset($project))
            <a href="{!! route('projects.smslog', $project->id) !!}" class="btn btn-primary navbar-btn @if(empty(request('section', $default = null))) active @endif">All</a>
            @foreach($project->sections as $key => $section)
                @if(!$section->disablesms)
                <a href="{!! route('projects.smslog', $project->id) !!}/?section={!! $key + 1 !!}" class="btn btn-primary navbar-btn @if(request('section', $default = null) == ($key + 1)) active @endif">SMS {!! $key + 1 !!}</a>
                @endif
            @endforeach
            <a href="{!! route('projects.smslog', $project->id) !!}/?section=unknown" class="btn btn-primary navbar-btn @if(request('section', $default = null) == 'unknown') active @endif">Unknown</a>
        @endif
    </section>

    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                @include('sms_logs.table')
            </div>
        </div>
    </div>
@endsection

@push('document-ready')
window.LaravelDataTables["dataTableBuilder"].columns.adjust().draw();
setInterval( function () {
window.LaravelDataTables["dataTableBuilder"].ajax.reload( null, false ); // user paging is not reset on reload
}, 10000 );
ajaxoverlay = false;
$('#project').on('change', function(e){
var filterurl = $(this).val();

window.location.href = filterurl;
});
@endpush

resources/views/sms_logs/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Sms Log
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('sms_logs.show_fields')
                    <a href="{!! route('smsLogs.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/sms_logs/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $smsLog->id !!}</p>
</div>

<!-- Service Id Field -->
<div class="form-group">
    {!! Form::label('service_id', 'Service Id:') !!}
    <p>{!! $smsLog->service_id !!}</p>
</div>

<!-- From Number Field -->
<div class="form-group">
    {!! Form::label('from_number', 'From Number:') !!}
    <p>{!! $smsLog->from_number !!}</p>
</div>

<!-- To Number Field -->
<div class="form-group">
    {!! Form::label('to_number', 'To Number:') !!}
    <p>{!! $smsLog->to_number !!}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $smsLog->name !!}</p>
</div>

<!-- Content Field -->
<div class="form-group">
    {!! Form::label('content', 'Content:') !!}
    <p>{!! $smsLog->content !!}</p>
</div>

<!-- Error Message Field -->
<div class="form-group">
    {!! Form::label('error_message', 'Error Message:') !!}
    <p>{!! $smsLog->error_message !!}</p>
</div>

<!-- Search Result Field -->
<div class="form-group">
    {!! Form::label('search_result', 'Search Result:') !!}
    <p>{!! $smsLog->search_result !!}</p>
</div>

<!-- Phone Field -->
<div class="form-group">
    {!! Form::label('phone', 'Phone:') !!}
    <p>{!! $smsLog->phone !!}</p>
</div>

resources/views/sms_logs/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection